version: 1
formatters:
  simple:
    format: '[%(asctime)s] [%(levelname)s] [%(filename)s] - %(funcName)s function at line %(lineno)d - %(message)s' 
    level: logging.INFO
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
root:
  handlers: [console]

disable_existing_loggers: false